name: expanding_cards_example
publish_to: none
description: Demonstrates how to use the expanding_cards plugin.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.0
  logging_config: ^0.6.7+7
  logging: ^1.0.2
  cupertino_icons: ^1.0.4
  flutter: 
    sdk: flutter
  sunny_essentials: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_essentials
  expanding_cards: 
    path: /Users/ericm/sunny/player_rank/packages/expanding_cards
dev_dependencies: 
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  provider: ^6.0.2
flutter: 
  uses-material-design: true
