name: expanding_cards_example
publish_to: none
description: Demonstrates how to use the expanding_cards plugin.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.0
  logging: ^1.0.2
  cupertino_icons: ^1.0.4
  logging_config: 
    git: 
      url: git@github.com:SunnyApp/logging_config
      ref: trippi_app
  flutter: 
    sdk: flutter
  sunny_essentials: 
    git: 
      url: git@github.com:ericmartineau/sunny_essentials.git
      ref: trippi_app
  expanding_cards: 
    git: 
      url: git@github.com:SunnyApp/expanding_cards
      ref: trippi_app
dev_dependencies: 
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  provider: ^6.0.2
flutter: 
  uses-material-design: true
