name: expanding_cards_example
publish_to: none
description: Demonstrates how to use the expanding_cards plugin.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.3
  logging: 1.2.0
  cupertino_icons: ^1.0.5
  logging_config: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/logging_config
  flutter: 
    sdk: flutter
  sunny_essentials: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/sunny_essentials
  expanding_cards: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/expanding_cards
dev_dependencies: 
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  provider: ^6.0.5
flutter: 
  uses-material-design: true
