name: expanding_cards
version: 0.8.0+6
homepage: https://github.com/SunnyApp/expanding_cards
description: Cards that expand when you tap on them
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  provider: ^6.0.2
  logging: ^1.0.2
  matrix4_transform: ^2.0.1
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  sunny_essentials: 
    git: 
      url: git@github.com:ericmartineau/sunny_essentials.git
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
