name: expanding_cards
version: 0.4.4
description: Cards that expand when you tap on them
homepage: https://github.com/SunnyApp/expanding_cards

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  background_app_bar: ^1.0.2
  sunny_dart: ^0.5.8+3
  provider: ^4.3.2+2
  matrix4_transform: ^1.1.6
  sunny_core_widgets:
    path: ../sunny_core_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sunny_core_widgets:
    path: ../sunny_core_widgets

#  sunny_forms:
#    path: ../sunny_forms
#  waypoints:
#    path: ../sunny_entities/waypoints

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
