name: expanding_cards
version: 0.8.0+5
homepage: https://github.com/SunnyApp/expanding_cards
description: Cards that expand when you tap on them
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  provider: ^6.0.1
  logging: ^1.0.2
  dartxx: ^0.5.3+2
  matrix4_transform: ^2.0.1
  sunny_essentials: ^0.8.0+13
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
