name: expanding_cards
version: 0.6.0+2
homepage: https://github.com/SunnyApp/expanding_cards
description: Cards that expand when you tap on them
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  provider: ^5.0.0
  logging: ^1.0.0
  dartxx: ^0.5.0+2
  matrix4_transform: ^2.0.0
  sunny_essentials: ^0.6.0+1
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
